version: 2

project_name: aws-ecr-client

before:
  hooks:
    - go mod download

builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64

archives:
- formats:
  - zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-snap"

changelog:
  use: github
