name: CI

on:
  push:
    tags: [ v* ]
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3.2.0
      with:
        version: v1.48

    - name: Prepare a snapshot release
      if: "!startsWith(github.ref, 'refs/tags/v')"
      uses: goreleaser/goreleaser-action@v3
      with:
        version: latest
        args: release --rm-dist --snapshot
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Release a new version
      if: startsWith(github.ref, 'refs/tags/v')
      uses: goreleaser/goreleaser-action@v3
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Artifacts to releases.fivexl.io
      if: startsWith(github.ref, 'refs/tags/v')
      env:
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: aws s3 sync ./dist/ s3://${{ secrets.RELEASE_BUCKET }}/aws-ecr-client-golang/ --exclude="*.zip" --include="checksums.txt"
